/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package taufikjuice;

import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import method.beli.belicontrol;
import method.beli.databeli;
import method.datajuice.DataJuice;
import method.datajuice.JuiceControl;

/**
 *
 * @author ASUS
 */
public class penjualan extends javax.swing.JFrame {

    /**
     * Creates new form penjualan
     */
    public penjualan() {
        initComponents();
        tstok.setVisible(false);
        tombolHiden();
        hiden();
    }
    
    private void siapIsi(boolean a){
        tgltransaksi.setEnabled(a);
        tstok.setEnabled(a);
        nmpembeli.setEnabled(a);
        kdjuice.setEnabled(a);
        nmjuice.setEnabled(a);
        hrgjual.setEnabled(a);
        jmlbeli.setEnabled(a);
    }
    
    private void bersih(){
        kdjuice.setText(null);
        nmpembeli.setText(null);
        nmjuice.setText(null);
        hrgjual.setText(null);
        jmlbeli.setText(null);
        ttotal.setText("0");
        ttunai.setText("0");
        tkembali.setText("0");
    }
    
    public void hiden(){
        tstok.setEnabled(false);
        kdjuice.setEnabled(false);
        nmjuice.setEnabled(false);
        hrgjual.setEnabled(false);
    }
    
    public void tampiltanggal(){
        DateFormat tgl = new SimpleDateFormat("dd/MMMM/yyyy");
        String htgl=tgl.format(Calendar.getInstance().getTime());
        tgltransaksi.setText(htgl);
    }
    
    private void buatNoNota(){
        ListDb=bc.tampil();
        if(ListDb.isEmpty()){
            tstok.setText("N-"+1);
        }else{
            int a= ListDb.size()-1;
            int no=Integer.parseInt(ListDb.get(a).getnonota().replace("N-", ""))+1;
            tstok.setText("No-"+no);
            tstok.setEnabled(false);
        }
    }
    
    public void tombolHiden(){
        btntambah.setEnabled(false);
        btnkurang.setEnabled(false);
        tgltransaksi.setEnabled(false);
    }
    
    public void tombolNormal(){
        btntambah.setEnabled(false);
        btnkurang.setEnabled(false);
    }
    
    private void buattableModel(){
        model = new DefaultTableModel();
        model.addColumn("Kode Juice");
        model.addColumn("Nama Juice");
        model.addColumn("Satuan");
        model.addColumn("Harga");
        jTable2.setModel(model);
    }
    
    private void tampiljuice() throws SQLException{
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        ListJuice.clear();
        ListJuice=jc.tampil();
        for (int x = 0; x< ListJuice.size(); x++){
            Object[] data = new Object[4];
            data[0]=ListJuice.get(x).getKdjuice();
            data[1]=ListJuice.get(x).getNmjuice();
            data[2]=ListJuice.get(x).getSatuan();
            data[3]=ListJuice.get(x).getHarga();
            model.addRow(data);
        }
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        txtcari1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        ttotal = new javax.swing.JTextField();
        ttunai = new javax.swing.JTextField();
        tkembali = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btntambah = new javax.swing.JButton();
        btnkurang = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tgltransaksi = new javax.swing.JTextField();
        nmpembeli = new javax.swing.JTextField();
        kdjuice = new javax.swing.JTextField();
        nmjuice = new javax.swing.JTextField();
        hrgjual = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jmlbeli = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnpilih = new javax.swing.JButton();
        btnsimpan = new javax.swing.JButton();
        btntambahjuice = new javax.swing.JButton();
        tstok = new javax.swing.JTextField();
        nonota = new javax.swing.JTextField();

        jDialog1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(102, 255, 255));

        jLabel6.setFont(new java.awt.Font("Ink Free", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Data Juice ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(113, 113, 113))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jDialog1.getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 60));

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));

        jTable2.setBackground(new java.awt.Color(0, 102, 102));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        txtcari1.setBackground(new java.awt.Color(0, 102, 102));
        txtcari1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcari1KeyReleased(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Ink Free", 1, 24)); // NOI18N
        jLabel13.setText("Cari Data Juice :");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtcari1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jLabel13)
                    .addContainerGap(245, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(txtcari1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                    .addContainerGap(181, Short.MAX_VALUE)
                    .addComponent(jLabel13)
                    .addGap(19, 19, 19)))
        );

        jDialog1.getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 450, 230));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Californian FB", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconcrud/juice.png"))); // NOI18N
        jLabel1.setText("TRANSAKSI PENJUALAN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, -1, 100));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -3, 910, 100));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(102, 255, 255));

        jTable1.setBackground(new java.awt.Color(0, 102, 102));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Ink Free", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Total");

        ttotal.setBackground(new java.awt.Color(0, 102, 102));

        ttunai.setBackground(new java.awt.Color(0, 102, 102));

        tkembali.setBackground(new java.awt.Color(0, 102, 102));

        jLabel3.setFont(new java.awt.Font("Ink Free", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Bayar");

        jLabel4.setFont(new java.awt.Font("Ink Free", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Kembali");

        btntambah.setBackground(new java.awt.Color(102, 255, 255));
        btntambah.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btntambah.setText("+");

        btnkurang.setBackground(new java.awt.Color(102, 255, 255));
        btnkurang.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnkurang.setText("-");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btntambah, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnkurang, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tkembali, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ttunai, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(71, 71, 71)
                        .addComponent(ttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnkurang, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ttunai, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tkembali, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(29, 29, 29))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 470, 370));

        jLabel7.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("No Nota");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel8.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Nama Pembeli");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel9.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Kode Juice");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel10.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Nama Juice");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel11.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Harga Jual");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        tgltransaksi.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.add(tgltransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 190, 34));

        nmpembeli.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.add(nmpembeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 190, 34));

        kdjuice.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.add(kdjuice, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 90, 34));

        nmjuice.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.add(nmjuice, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 190, 34));

        hrgjual.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.add(hrgjual, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 190, 34));

        jLabel12.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Jumlah Beli");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, 20));

        jmlbeli.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.add(jmlbeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 190, 34));

        jLabel5.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Tanggal Transaksi");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        btnpilih.setBackground(new java.awt.Color(0, 102, 102));
        btnpilih.setFont(new java.awt.Font("Ink Free", 1, 18)); // NOI18N
        btnpilih.setText("Pilih");
        btnpilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpilihActionPerformed(evt);
            }
        });
        jPanel2.add(btnpilih, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, -1, -1));

        btnsimpan.setBackground(new java.awt.Color(0, 102, 102));
        btnsimpan.setFont(new java.awt.Font("Ink Free", 1, 18)); // NOI18N
        btnsimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconcrud/print.png"))); // NOI18N
        btnsimpan.setText("Simpan");
        btnsimpan.setBorder(null);
        jPanel2.add(btnsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, -1, -1));

        btntambahjuice.setBackground(new java.awt.Color(0, 102, 102));
        btntambahjuice.setFont(new java.awt.Font("Ink Free", 1, 18)); // NOI18N
        btntambahjuice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconcrud/plus.png"))); // NOI18N
        btntambahjuice.setText("Tambah");
        btntambahjuice.setBorder(null);
        btntambahjuice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahjuiceActionPerformed(evt);
            }
        });
        jPanel2.add(btntambahjuice, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        tstok.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.add(tstok, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 80, 34));

        nonota.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.add(nonota, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 80, 34));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 910, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btntambahjuiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahjuiceActionPerformed
        if (btntambahjuice.getText().equalsIgnoreCase("Tambah")){
            btntambahjuice.setText("Batal");
            siapIsi(true);
            bersih();
            hiden();
            tampiltanggal();
            buatNoNota();
            nmpembeli.requestFocus();
            btntambah.setEnabled(true);
            btnkurang.setEnabled(true);
            tgltransaksi.setEnabled(false);
        }else{
            bersih();
            siapIsi(false);
            btntambahjuice.setText("Tambah");
            tombolNormal();
            bersih();
            tstok.setText(null);
            tgltransaksi.setText(null);
        }
    }//GEN-LAST:event_btntambahjuiceActionPerformed

    private void btnpilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpilihActionPerformed
        buattableModel();
        try {
            tampiljuice();
        } catch (SQLException ex) {
            Logger.getLogger(penjualan.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtcari1.setText(null);
        jDialog1.setVisible(true);
        jDialog1.setBounds(300, 300, 472, 390);
        txtcari1.requestFocus();
    }//GEN-LAST:event_btnpilihActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        int baris = jTable2.getSelectedRow();
        kdjuice.setText(jTable2.getModel().getValueAt(baris, 0).toString());
        nmjuice.setText(jTable2.getModel().getValueAt(baris, 1).toString());
        tstok.setText(jTable2.getModel().getValueAt(baris, 2).toString());
        hrgjual.setText(jTable2.getModel().getValueAt(baris, 3).toString());
        jmlbeli.requestFocus();
        jDialog1.setVisible(false);
        
    }//GEN-LAST:event_jTable2MouseClicked

    private void txtcari1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcari1KeyReleased
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        ListJuice.clear();
        ListJuice=jc.cariJuice(txtcari1.getText());
        for (int x=0; x< ListJuice.size(); x++){
            Object[] data = new Object[4];
            data[0]=ListJuice.get(x).getKdjuice();
            data[1]=ListJuice.get(x).getNmjuice();
            data[2]=ListJuice.get(x).getSatuan();
            data[3]=ListJuice.get(x).getHarga();
            model.addRow(data);
        }
    }//GEN-LAST:event_txtcari1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new penjualan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnkurang;
    private javax.swing.JButton btnpilih;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btntambah;
    private javax.swing.JButton btntambahjuice;
    private javax.swing.JTextField hrgjual;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jmlbeli;
    private javax.swing.JTextField kdjuice;
    private javax.swing.JTextField nmjuice;
    private javax.swing.JTextField nmpembeli;
    private javax.swing.JTextField nonota;
    private javax.swing.JTextField tgltransaksi;
    private javax.swing.JTextField tkembali;
    private javax.swing.JTextField tstok;
    private javax.swing.JTextField ttotal;
    private javax.swing.JTextField ttunai;
    private javax.swing.JTextField txtcari1;
    // End of variables declaration//GEN-END:variables

    private DefaultTableModel model;
    belicontrol bc = new belicontrol();
    JuiceControl jc = new JuiceControl();
    
    List<databeli> ListDb= new ArrayList<databeli>();
    List<DataJuice> ListJuice= new ArrayList<DataJuice>();
}

